# Generated by Django 3.2.6 on 2022-06-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20220613_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Workplace',
            field=models.TextField(blank=True),
        ),
    ]
