# Generated by Django 3.2.6 on 2022-06-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_profile_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Relationship_status',
            field=models.IntegerField(choices=[('0', 'None'), ('1', 'Single'), ('2', 'In a relationship'), ('3', 'Married'), ('4', 'Engaged')], null=True),
        ),
    ]
