# Generated by Django 4.0.5 on 2022-06-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_alter_profile_relationship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Relationship_status',
            field=models.CharField(choices=[('no', 'None'), ('Si', 'Single'), ('In', 'In a relationship'), ('Ma', 'Married'), ('En', 'Engaged')], default='no', max_length=2),
        ),
    ]
