# Generated by Django 4.0.5 on 2022-06-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0011_alter_profile_relationship_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Relationship_status',
        ),
    ]
