# Generated by Django 4.0.5 on 2022-06-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0020_alter_profile_relationship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_profileimage',
            field=models.ImageField(default='blank-profile-picture.png', upload_to=''),
        ),
    ]
