# Generated by Django 4.0.5 on 2022-06-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0021_post_user_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='like_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
